### ISSUE TITLE
How do I set up the Author for the articles

### ISSUE THREAD

**Issue by ganar** [absalomedia/grav-theme-future#5]
The author taxonomy —set either globally for the site, or locally in each page— for the content does not seem to work in the template. How should this be setup?

Thanks a lot for your help

**Comment by absalomedia** [comment]
It should automatically inherit from the blog author - the code expressly states:
`page.header.author`

At this time the avatar still remains hardcoded

**Comment by ganar** [comment]
_Noob_ question: Can you tell me if the frontmatter for my articles is correct? The system is not taking the general author configuration, Grav and my system is up to date (PHP Version 5.5.31)

```
title: 'Pasta con brócoli'
published: true
header_image: '1'
header_image_file: pasta-brocoli.jpg
summary:
    enabled: '1'
    format: short
taxonomy:
    author:
        - 'Kristina Wetter'
    tag:
        - 'Aceite de Oliva'
        - ajo
        - 'queso parmesano'
        - pasta
        - brócoli
        - tomate
    category:
        - Recetas
```

And here is the global configuration section detailing the author

![kw-author-conf](https://cloud.githubusercontent.com/assets/431185/14921696/3ecf7520-0dfd-11e6-82c2-2de9ff556959.png)
